<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9b960e98-011d-489e-8b63-bc8127612625</UserSecretsId>
    <!-- <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS> -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CRM.App.Web.Client\CRM.App.Web.Client.csproj" />
    <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MudBlazor" Version="9.1.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="4.0.0" />
    <PackageReference Include="MudBlazor.Translations" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
  </ItemGroup>

	<!--<ItemGroup>
		<ProjectReference Include="C:\Users\oscar\source\repos\CRM\CRM.Dtos\CRM.Dtos.csproj" />
	</ItemGroup>

	 <ItemGroup>
    <Reference Include="CRM.Dtos">
      <HintPath>..\..\..\CRM\CRM.Dtos\bin\Debug\net9.0\CRM.Dtos.dll</HintPath>
    </Reference>
  </ItemGroup>-->

</Project>