<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>1.0.1</AssemblyVersion>
	<!-- <UseMaui>true</UseMaui> -->
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Blazored.Modal" Version="7.3.1" />
    <PackageReference Include="ExcelDataReader" Version="3.8.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Forms" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.14.0" />
    <PackageReference Include="MudBlazor" Version="9.1.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="4.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
	<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.14.0" />
	<PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.13.2" />
  </ItemGroup>

  <!--<ItemGroup Condition="">
    <ProjectReference Include="../CRM_REPO/CRM.Dtos/CRM.Dtos.csproj" />
  </ItemGroup>-->

	<ItemGroup>
		<ProjectReference Include="C:\Users\oscar\source\repos\CRM\CRM.Dtos\CRM.Dtos.csproj" />

		<!--<ProjectReference Include="../CRM_REPO/CRM.Dtos/CRM.Dtos.csproj" 
						  Condition="'$(GITHUB_ACTIONS)' == 'true'" />

		<ProjectReference Include="C:\Users\oscar\source\repos\CRM\CRM.Dtos\CRM.Dtos.csproj" 
						  Condition="'$(GITHUB_ACTIONS)' != 'true'" />-->
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Pages\Utilidades\" />
	</ItemGroup>
	
</Project>
