name: Deploy Blazor WASM to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Checkout Dtos
        uses: actions/checkout@v4
        with:
          repository: osmaga2012/CRM # El nombre real de tu repo de DTOs
          path: CRM_REPO # Esto crea la carpeta que espera el .csproj
          # Si el repo de DTOs es PRIVADO, añade la línea de abajo:
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # Cambia a 7.0 o 9.0 si usas otra versión

      - name: Publish App
        # Esto compila el proyecto y genera los archivos finales en la carpeta 'release'
        run: dotnet publish CRM.App.Web.Client/CRM.App.Web.Client.csproj -c Debug -o debug /p:StaticWebAssetsEnabled=true
        #run: dotnet publish CRM.App.Web/CRM.App.Web.csproj -c Release -o release

      - name: Fix for GitHub Pages
        run: |
          # 1. Creamos el nojekyll
          touch debug/wwwroot/.nojekyll
          
          # 2. Forzamos el cambio del base href sin importar qué hubiera antes
          # Buscamos la línea que contiene 'base href' y la reemplazamos entera
          sed -i '/base href=/c\    <base href="/CRM_V2/" />' debug/wwwroot/index.html
          
          # 3. Copiamos a 404
          cp debug/wwwroot/index.html debug/wwwroot/404.html
          
      - name: List files (Diagnostic)
        run: |
          echo "Contenido de debug/wwwroot:"
          ls -R release/wwwroot
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # IMPORTANTE: Solo subimos la carpeta wwwroot resultante de la publicación
          path: 'debug/wwwroot'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
